version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cq5qbqlds78s73d644g0-a.oregon-postgres.render.com:5432/paydebt
      SPRING_DATASOURCE_USERNAME: jeff
      SPRING_DATASOURCE_PASSWORD: nXIvKtguSA835J2mg9rHnGwbVTLNU6DD

volumes:
  db-data:
