# Blueprint para desplegar en Render
# Documentación: https://render.com/docs/blueprint-spec

# 1. Definición de la Base de Datos
databases:
  - name: paygrid-postgres
    region: oregon
    plan: free

# 2. Definición de los Servicios Web
services:
  - type: web
    name: whatsapp-bridge
    region: oregon
    plan: free
    env: docker
    dockerContext: ./whatsapp-bridge
    dockerfilePath: ./whatsapp-bridge/Dockerfile

  - type: web
    name: backend-app
    region: oregon
    plan: free
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        value: jdbc:$(fromDatabase.paygrid-postgres.connectionString)
      - key: DB_USERNAME
        fromDatabase:
          name: paygrid-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: paygrid-postgres
          property: password
      - key: WPPCONNECT_BASE_URL
        value: http://whatsapp-bridge:21465/api
      - key: DDL_AUTO
        value: update
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
