# Blueprint para desplegar en Render
# Documentación: https://render.com/docs/blueprint-spec

# 1. Definición de la Base de Datos
# Las bases de datos tienen su propia sección de nivel superior.

databases:
  - name: paygrid-postgres # Nombre para referenciar desde otros servicios
    region: oregon
    plan: free

# 2. Definición de los Servicios Web
# Aquí van tus aplicaciones que se ejecutan con Docker.

services:
  - type: web
    name: whatsapp-bridge
    region: oregon
    plan: free
    env: docker
    dockerContext: ./whatsapp-bridge
    dockerfilePath: ./whatsapp-bridge/Dockerfile
    disk:
      name: whatsapp-tokens
      mountPath: /usr/src/app/tokens
      sizeGB: 1

  - type: web
    name: backend-app
    region: oregon
    plan: free
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      # Las variables 'fromDatabase' apuntan al 'name' definido en la sección 'databases'
      - key: DB_URL
        fromDatabase:
          name: paygrid-postgres
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: paygrid-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: paygrid-postgres
          property: password
      - key: WPPCONNECT_BASE_URL
        value: http://whatsapp-bridge:21465/api
      - key: DDL_AUTO
        value: update
      # --- Claves Secretas ---
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_KEY
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
